# Generated by Django 6.0.2 on 2026-02-11 15:09

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=20)),
                ('otp', models.CharField(max_length=6)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'phone_otps',
                'indexes': [models.Index(fields=['phone'], name='phone_otps_phone_55f92c_idx'), models.Index(fields=['expires_at'], name='phone_otps_expires_3b8e5e_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('countries', models.JSONField(default=list)),
                ('degree', models.CharField(max_length=100)),
                ('fields', models.JSONField(default=list)),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('10.00'))])),
                ('grad_year', models.CharField(max_length=4)),
                ('budget_lakh', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('ai_score', models.IntegerField(blank=True, null=True)),
                ('ai_result', models.JSONField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'student_profiles',
                'indexes': [models.Index(fields=['phone'], name='student_pro_phone_c3cbc7_idx'), models.Index(fields=['is_verified'], name='student_pro_is_veri_fc35f2_idx'), models.Index(fields=['created_at'], name='student_pro_created_cc0720_idx')],
            },
        ),
    ]
