# Generated by Django 6.0.2 on 2026-02-11 17:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='studentprofile',
            name='student_pro_is_veri_fc35f2_idx',
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in format '+999999999'.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='ai_result',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='ai_score',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='budget_lakh',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='cgpa',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='countries',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='fields',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='grad_year',
        ),
    ]
